AllCops:
  TargetRubyVersion: 3.0

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Layout/LineLength:
  Exclude:
    - 'spec/**/*_spec.rb'

Naming/FileName:
  Exclude:
    - 'lib/i18n-ai.rb'

Metrics/BlockLength:
  Exclude:
    - 'i18n-ai.gemspec'
    - 'spec/**/*_spec.rb'

Style/Documentation:
  Enabled: false

Style/BlockDelimiters:
  Exclude:
    - 'spec/**/*_spec.rb'
